Update release script.  Needs new git to use git-tag -u, and needs an env. var GIT_GPG_KEY to use with -u.

diff --git a/scripts/dorelease b/scripts/dorelease
--- a/scripts/dorelease
+++ b/scripts/dorelease
@@ -7,6 +7,14 @@ if [ $# -ne 1 ]; then
 	exit 1
 fi
 
+if [ -z "${GIT_GPG_KEY}" ]; then
+	echo -e "Error:\tMust set GIT_GPG_KEY env variable"
+	exit 1
+fi
+
+git-tag -u "${GIT_GPG_KEY}" -m "this is a TEST" vTest
+exit 0
+
 RELEASE=$1
 REL_ARRAY=(${RELEASE//./ })
 BASE=${REL_ARRAY[0]}.${REL_ARRAY[1]}.${REL_ARRAY[2]}
@@ -29,7 +37,7 @@ quilt series | while read PATCH
 do
 	cat $PATCH >> $RELDIR/apply.mbox
 done
-dotest $RELDIR/apply.mbox
+git-applymbox $RELDIR/apply.mbox
 rm $RELDIR/apply.mbox
 
 # update EXTRAVERSION
@@ -50,7 +58,7 @@ RELEASE_COMMIT=$(echo "Linux $RELEASE" | git-commit-tree $(git-write-tree) -p HE
 echo $RELEASE_COMMIT > .git/HEAD
 
 # tag it
-git-tag-script -s -m "This is the $RELEASE stable release" v$RELEASE
+git-tag-script -u ${GIT_GPG_KEY} -m "This is the $RELEASE stable release" v$RELEASE
 
 BASE_COMMIT="$(git-cat-file tag $(cat .git/refs/tags/v${BASE}) | grep object | cut -d" " -f2)"
 LAST_COMMIT="$(git-cat-file tag $(cat .git/refs/tags/v${LAST_REL}) | grep object | cut -d" " -f2)"
