scripts/quilt-mail: check to see if 'git quiltimport' succeeds or not
was causing trees to be created that should not have been.

Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

diff --git a/scripts/quilt-mail b/scripts/quilt-mail
--- a/scripts/quilt-mail
+++ b/scripts/quilt-mail
@@ -50,6 +50,10 @@ git clone -s . ${TMP_TREE}
 cd ${TMP_TREE}
 git checkout -b temp_branch
 git quiltimport --patches=${STABLE_QUEUE}/queue-${ROOT_VERSION}
+if [ $? -ne 0 ]; then
+	echo "git quilt import failed!!!"
+	exit 1
+fi
 
 # Apply the Makefile patch and commit it
 patch -p1 < ${TMP_DIR}/Makefile.patch
