scripts: quilt-mail: fix up for any number of patches in a series
Things broke for when over 1000 emails were sent out as the 000 email
did not get the proper list of cc: on it.

Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

diff --git a/scripts/quilt-mail b/scripts/quilt-mail
--- a/scripts/quilt-mail
+++ b/scripts/quilt-mail
@@ -147,6 +147,22 @@ ${STABLE_QUEUE}/scripts/mbox2send ${ROOT_VERSION} ${FULL_VERSION} ${MBOX}
 #< ${MBOX}.new formail -ds sh -c 'cat > msg.$FILENO'
 splitmbox.py ${MBOX}.new .
 
+# find the "0" email message
+if [ -f "msg.0" ]; then
+	MSG="msg.0"
+elif [ -f "msg.00" ]; then
+	MSG="msg.00"
+elif [ -f "msg.000" ]; then
+	MSG="msg.000"
+elif [ -f "msg.0000" ]; then
+	MSG="msg.0000"
+else
+	echo "mbox.ZERO can not be found???"
+	echo "Aborting!"
+	exit 1
+fi
+echo "MSG=${MSG}"
+
 # Add Linus and Andrew and others to the first email only:
 #sed -i -e "s/Cc: alan@lxorguk\.ukuu\.org\.uk/Cc: torvalds@linux-foundation\.org, akpm@linux-foundation\.org, alan@lxorguk\.ukuu\.org\.uk/" ${TMP_DIR}/msg.000
 #sed -i -e "s/Cc: stable@vger\.kernel\.org/Cc: torvalds@linux-foundation\.org, akpm@linux-foundation\.org, stable@vger\.kernel\.org/" ${TMP_DIR}/msg.000
@@ -160,7 +176,8 @@ splitmbox.py ${MBOX}.new .
 #sed -i -e "s/Cc: stable@vger\.kernel\.org/Cc: torvalds@linux-foundation\.org, akpm@linux-foundation\.org, linux@roeck-us\.net, shuah@kernel\.org, patches@kernelci\.org, lkft-triage@lists\.linaro\.org, pavel@denx\.de, stable@vger\.kernel\.org/" ${TMP_DIR}/msg.000
 #sed -i -e "s/Cc: stable@vger\.kernel\.org/Cc: torvalds@linux-foundation\.org, akpm@linux-foundation\.org, linux@roeck-us\.net, shuah@kernel\.org, patches@kernelci\.org, lkft-triage@lists\.linaro\.org, pavel@denx\.de, jonathanh@nvidia\.com, stable@vger\.kernel\.org/" ${TMP_DIR}/msg.000
 #sed -i -e "s/Cc: stable@vger\.kernel\.org/Cc: torvalds@linux-foundation\.org, akpm@linux-foundation\.org, linux@roeck-us\.net, shuah@kernel\.org, patches@kernelci\.org, lkft-triage@lists\.linaro\.org, pavel@denx\.de, jonathanh@nvidia\.com, f\.fainelli@gmail\.com, stable@vger\.kernel\.org/" ${TMP_DIR}/msg.000
-sed -i -e "s/Cc: stable@vger\.kernel\.org/Cc: torvalds@linux-foundation\.org, akpm@linux-foundation\.org, linux@roeck-us\.net, shuah@kernel\.org, patches@kernelci\.org, lkft-triage@lists\.linaro\.org, pavel@denx\.de, jonathanh@nvidia\.com, f\.fainelli@gmail\.com, sudipm\.mukherjee@gmail\.com, stable@vger\.kernel\.org/" ${TMP_DIR}/msg.000
+#sed -i -e "s/Cc: stable@vger\.kernel\.org/Cc: torvalds@linux-foundation\.org, akpm@linux-foundation\.org, linux@roeck-us\.net, shuah@kernel\.org, patches@kernelci\.org, lkft-triage@lists\.linaro\.org, pavel@denx\.de, jonathanh@nvidia\.com, f\.fainelli@gmail\.com, sudipm\.mukherjee@gmail\.com, stable@vger\.kernel\.org/" ${TMP_DIR}/msg.000
+sed -i -e "s/Cc: stable@vger\.kernel\.org/Cc: torvalds@linux-foundation\.org, akpm@linux-foundation\.org, linux@roeck-us\.net, shuah@kernel\.org, patches@kernelci\.org, lkft-triage@lists\.linaro\.org, pavel@denx\.de, jonathanh@nvidia\.com, f\.fainelli@gmail\.com, sudipm\.mukherjee@gmail\.com, stable@vger\.kernel\.org/" ${TMP_DIR}/${MSG}
 
 
 # Create a script to upload the patch to kernel.org and to send the patches out
@@ -169,10 +186,10 @@ echo "kup --host=git@gitolite.kernel.org --subcmd=kup-server put patch-${FULL_VE
 
 if [ "${RC}" == "rc1" ] ; then
 	echo "git send-email msg.*" >> ${TMP_DIR}/send_it_off
-	echo "#git send-email msg.000" >> ${TMP_DIR}/send_it_off
+	echo "#git send-email ${MSG}" >> ${TMP_DIR}/send_it_off
 else
 	echo "#git send-email msg.*" >> ${TMP_DIR}/send_it_off
-	echo "git send-email msg.000" >> ${TMP_DIR}/send_it_off
+	echo "git send-email ${MSG}" >> ${TMP_DIR}/send_it_off
 fi
 
 chmod 755 ${TMP_DIR}/send_it_off
